[tools]
"tuist" = "3.36.3"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"swift" = "5.9.2"

[tasks."build"]
description = "Builds the package using the Swift Package Manager"
run = "./make/tasks/workspace/build.sh"

[tasks."lint"]
description = "Lints the codebase"
run = "./make/tasks/workspace/lint.sh"

[tasks."lint:fix"]
description = "Lints the codebase fixing the fixable issues"
run = "./make/tasks/workspace/lint-fix.sh"

[tasks."lint:lockfiles"]
description = 'Lints the Package.resolved files to ensure they are consistent'
run = "./make/tasks/workspace/lint/lockfiles.sh"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"