name: SwiftTerminal

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: swift-terminal-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          experimental: true
      - name: Run
        run: rtx run lint

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          experimental: true
      - name: Run
        run: rtx run lint

  lint-lockfiles:
    name: Lint lockfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          experimental: true
      - name: Run
        run: rtx run lint:lockfiles